version: '3.8'

x-healthcheck: &default-healthcheck
  interval: 30s
  retries: 5

x-service-defaults: &service-defaults
  build:
    args:
      BUILD_ENV: production

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - backend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
    deploy:
      resources:
        limits:
          memory: 16g
          
  api:
    <<: *service-defaults
    build:
      context: ../services/api
    ports:
      - 8000:8000
    env_file: ../services/api/.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - backend
      - frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]

  web:
    <<: *service-defaults
    build:
      context: ../services/web
    ports:
      - 5000:5000
    env_file: ../services/web/.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]

networks:
  frontend:
  backend:

volumes:
  elasticsearch-data: