x-healthcheck: &default-healthcheck
  interval: 5s
  retries: 10

# Base service configuration
x-ollama: &ollama-base
  hostname: ollama
  image: ollama/ollama:latest
  pull_policy: always
  tty: true
  restart: unless-stopped
  ports:
    - 21240:11434
  environment:
    - OLLAMA_KEEP_ALIVE=24h
  volumes:
    - ollama-data:/root/.ollama
  networks:
    - default

services:
  # NVIDIA GPU configuration
  ollama-nvidia:
    <<: *ollama-base
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    profiles:
      - nvidia

  # AMD GPU configuration (with ROCm)
  ollama-amd:
    <<: *ollama-base
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
    profiles:
      - amd

  elasticsearch: &elasticsearch-base
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    ports:
      - 21220:9200
    environment:
      - node.name=elasticsearch
      - cluster.name=es-chipper-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=http://localhost:21230"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - default
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
    deploy:
      resources:
        limits:
          memory: 8g

networks:
  default:
    name: chipper_network

volumes:
  ollama-data:
  elasticsearch-data:
