x-healthcheck: &default-healthcheck
  interval: 1s
  retries: 60

x-service-defaults: &service-defaults
  build:
    args:
      BUILD_ENV: production

services:
  ollama:
    volumes:
      - ./volumes/ollama/data:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 8434:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - chipper-backend
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
    networks:
      - chipper-backend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
    deploy:
      resources:
        limits:
          memory: 16g

  elasticvue:
    image: cars10/elasticvue
    ports:
      - "8080:8080"
    environment:
      ELASTICVUE_CLUSTERS: '[{"name":"chipper","uri":"http://elasticsearch:9200"}]'
    restart: always
    networks:
      - chipper-backend

  chipper-api:
    <<: *service-defaults
    build:
      context: ../services/api
    ports:
      - 8000:8000
    env_file: ../services/api/.env
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - chipper-backend
      - chipper-frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]

  chipper-web:
    <<: *service-defaults
    build:
      context: ../services/web
    ports:
      - 5000:5000
    env_file: ../services/web/.env
    depends_on:
      chipper-api:
        condition: service_healthy
    networks:
      - chipper-frontend
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]

networks:
  chipper-frontend:
  chipper-backend:
